const crypto = require("node:crypto");
const { safeJson } = require("./connections-model.js");
const { dockyardThemeCss } = require("./ui-theme.js");

function renderConnectionsHtml(webview, model, backgroundUri = "") {
  const nonce = crypto.randomBytes(18).toString("base64url");
  const cspSource = webview?.cspSource || "'self'";
  return `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${cspSource} data:; style-src 'nonce-${nonce}' ${cspSource}; script-src 'nonce-${nonce}';"><title>DockyardOS Connections</title>
<style nonce="${nonce}">${dockyardThemeCss(backgroundUri)}
body{padding:24px}.wrap{max-width:1320px;margin:0 auto}.head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.title{font-size:25px;font-weight:760}.stats{display:flex;gap:7px;flex-wrap:wrap;margin:14px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:11px}.cardhead{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.card h3{margin:0;font-size:14px}.id{font:10px var(--vscode-editor-font-family);color:var(--dy-muted);margin-top:3px}.state{font-size:10px;padding:4px 8px;border-radius:999px;border:1px solid var(--dy-border)}.state.ready{color:#86efac;border-color:rgba(52,211,153,.30)}.state.partial{color:#fde68a;border-color:rgba(251,191,36,.30)}.state.warning{color:#fda4af;border-color:rgba(251,113,133,.30)}.state.muted{color:var(--dy-muted)}.detail{font-size:10px;color:var(--dy-muted);line-height:1.5;margin:9px 0;overflow-wrap:anywhere}.card .dy-actions{margin-top:10px}.signals{display:none;margin-top:9px}.signals.open{display:block}.signals div{font-size:10px;line-height:1.5}.ok{color:#86efac}.bad{color:var(--dy-muted)}.section{margin-top:20px}.section h2{font-size:16px;margin:0}.section-head{display:flex;align-items:end;justify-content:space-between;margin-bottom:10px}.notice{min-height:20px;color:var(--dy-muted);font-size:11px;margin-top:8px}@media(max-width:680px){body{padding:14px}.head{flex-direction:column}.grid{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="dy-hero"><div class="head"><div><div class="dy-kicker">Universal connectors</div><div class="title">Connections Center</div><div class="dy-sub">Connect project services without turning DockyardOS into a credential vault.</div></div><div class="dy-actions"><button class="secondary" id="refresh">Refresh local</button><button id="verify">Verify connections</button></div></div><div class="stats" id="stats"></div><div class="notice" id="notice"></div></div>
<div class="callout" id="safety" style="margin-top:12px"></div>
<section class="section"><div class="section-head"><div><h2>Provider accounts</h2><div class="dy-sub">Local detection is automatic. Live verification uses bounded read-only identity/status probes.</div></div></div><div class="grid" id="providers"></div></section>
<section class="section"><div class="section-head"><div><h2>MCP connectors</h2><div class="dy-sub">Configured is not the same as connected. Current-session use remains the source of connection truth.</div></div></div><div class="grid" id="mcps"></div></section></div>
<script nonce="${nonce}">
const vscode=acquireVsCodeApi();let model=${safeJson(model)};const $=id=>document.getElementById(id);const text=v=>document.createTextNode(String(v??''));
function button(label,type,id,secondary=false){const b=document.createElement('button');b.append(text(label));if(secondary)b.className='secondary';b.onclick=()=>{$('notice').textContent=label+'…';vscode.postMessage({type,id})};return b}
function stateBadge(status){const e=document.createElement('span');e.className='state '+(status.level||'muted');e.append(text(status.label||status.state||'Unknown'));return e}
function stat(label,value,kind=''){const e=document.createElement('span');e.className='dy-chip '+kind;e.append(text(label+': '+value));return e}
function renderStats(){const s=model.summary||{};$('stats').replaceChildren(stat('Providers',s.providers||0),stat('Ready',s.providerReady||0,s.providerReady?'good':''),stat('Needs setup/login',s.providerAttention||0,s.providerAttention?'warn':''),stat('MCPs',s.mcps||0),stat('No-auth MCPs',s.noAuthMcps||0,'info'))}
function renderSafety(){const root=$('safety');root.replaceChildren();for(const value of model.safety||[]){const d=document.createElement('div');d.append(text('• '+value));root.append(d)}}
function providerCard(p){const c=document.createElement('article');c.className='dy-card card';const h=document.createElement('div');h.className='cardhead';const title=document.createElement('div');const n=document.createElement('h3');n.append(text(p.name));const id=document.createElement('div');id.className='id';id.append(text(p.id));title.append(n,id);h.append(title,stateBadge(p.status));c.append(h);const d=document.createElement('div');d.className='detail';d.append(text((p.liveChecked?'Live checked · ':'Local only · ')+(p.installed?'CLI installed':'CLI not detected')+(p.configured?' · configured':'')+(p.authenticated?' · authenticated':'')+(p.linked?' · linked':'')));c.append(d);const a=document.createElement('div');a.className='dy-actions';if(p.canLogin)a.append(button(p.installed?'Login / reconnect':'Login after install','provider-login',p.id));if(p.setupUrl)a.append(button('Setup docs','provider-setup',p.id,true));if((p.signals||[]).length){const details=document.createElement('button');details.className='secondary';details.append(text('Details'));const box=document.createElement('div');box.className='signals';for(const s of p.signals){const row=document.createElement('div');row.className=s.ok?'ok':'bad';row.append(text((s.ok?'✓ ':'· ')+s.detail));box.append(row)}details.onclick=()=>box.classList.toggle('open');a.append(details);c.append(a,box)}else c.append(a);return c}
function mcpCard(m){const c=document.createElement('article');c.className='dy-card card';const h=document.createElement('div');h.className='cardhead';const title=document.createElement('div');const n=document.createElement('h3');n.append(text(m.name));const id=document.createElement('div');id.className='id';id.append(text(m.id));title.append(n,id);h.append(title,stateBadge(m.status));c.append(h);const chips=document.createElement('div');chips.className='dy-chips';const cat=document.createElement('span');cat.className='dy-chip';cat.append(text(m.category));chips.append(cat);if(m.auth==='none'){const noauth=document.createElement('span');noauth.className='dy-chip info';noauth.append(text('no auth'));chips.append(noauth)}c.append(chips);if(m.note){const d=document.createElement('div');d.className='detail';d.append(text(m.note));c.append(d)}if(m.endpoint){const d=document.createElement('div');d.className='detail mono';d.append(text(m.endpoint));c.append(d)}const a=document.createElement('div');a.className='dy-actions';if(m.setupCommand)a.append(button('Install / configure','mcp-command',m.id));if(m.setupUrl)a.append(button('Setup docs','mcp-setup',m.id,true));if(m.endpoint)a.append(button('Copy endpoint','mcp-copy-endpoint',m.id,true));c.append(a);return c}
function render(){renderStats();renderSafety();$('providers').replaceChildren(...(model.providers||[]).map(providerCard));$('mcps').replaceChildren(...(model.mcps||[]).map(mcpCard));$('notice').textContent=model.liveChecked?'Live connection verification completed.':'Showing local readiness only. Use Verify connections for read-only account checks.'}
$('refresh').onclick=()=>{$('notice').textContent='Refreshing local readiness…';vscode.postMessage({type:'refresh-local'})};$('verify').onclick=()=>{$('notice').textContent='Running read-only live checks…';vscode.postMessage({type:'verify-live'})};window.addEventListener('message',event=>{const m=event.data||{};if(m.type==='model'){model=m.model;render();if(m.notice)$('notice').textContent=m.notice}else if(m.type==='notice')$('notice').textContent=m.text||'';else if(m.type==='error')$('notice').textContent=m.message||'Operation failed.'});render();
</script></body></html>`;
}

module.exports = { renderConnectionsHtml };
