const crypto = require("node:crypto");
const { safeJson } = require("./connections-model.js");

function renderConnectionsHtml(webview, model) {
  const nonce = crypto.randomBytes(18).toString("base64url");
  const cspSource = webview?.cspSource || "'self'";
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}' ${cspSource}; script-src 'nonce-${nonce}';">
<title>DockyardOS Connections</title>
<style nonce="${nonce}">
*{box-sizing:border-box}body{margin:0;padding:22px;font-family:var(--vscode-font-family);color:var(--vscode-foreground);background:var(--vscode-editor-background)}button{font:inherit;border:0;border-radius:7px;padding:8px 12px;color:var(--vscode-button-foreground);background:var(--vscode-button-background);cursor:pointer}button:hover{background:var(--vscode-button-hoverBackground)}button.secondary{color:var(--vscode-button-secondaryForeground);background:var(--vscode-button-secondaryBackground)}h1{margin:0;font-size:25px}.sub,.muted,.detail{color:var(--vscode-descriptionForeground)}.header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.actions,.stats,.chips{display:flex;gap:8px;flex-wrap:wrap}.stats{margin:14px 0}.stat,.chip{font-size:12px;padding:4px 8px;border-radius:999px;background:var(--vscode-badge-background);color:var(--vscode-badge-foreground)}.notice{min-height:24px;margin:10px 0;color:var(--vscode-descriptionForeground)}.safety{border:1px solid var(--vscode-panel-border);border-left:3px solid var(--vscode-notificationsInfoIcon-foreground);border-radius:8px;padding:10px 13px;margin:14px 0;background:var(--vscode-editorWidget-background)}.safety div{font-size:12px;line-height:1.55}.section{margin-top:24px}.section h2{margin:0 0 6px;font-size:18px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(315px,1fr));gap:12px;margin-top:12px}.card{border:1px solid var(--vscode-panel-border);border-radius:10px;padding:14px;background:var(--vscode-editorWidget-background)}.cardhead{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.card h3{margin:0;font-size:16px}.id{font:12px var(--vscode-editor-font-family);color:var(--vscode-descriptionForeground);margin-top:3px}.state{font-size:12px;padding:4px 8px;border-radius:999px;white-space:nowrap}.state.ready{color:var(--vscode-testing-iconPassed);border:1px solid color-mix(in srgb,var(--vscode-testing-iconPassed) 55%,transparent)}.state.partial{color:var(--vscode-notificationsWarningIcon-foreground);border:1px solid color-mix(in srgb,var(--vscode-notificationsWarningIcon-foreground) 55%,transparent)}.state.warning{color:var(--vscode-errorForeground);border:1px solid color-mix(in srgb,var(--vscode-errorForeground) 55%,transparent)}.state.muted{color:var(--vscode-descriptionForeground);border:1px solid var(--vscode-panel-border)}.detail{font-size:12px;line-height:1.5;margin:9px 0;overflow-wrap:anywhere}.card .actions{margin-top:11px}.divider{border:0;border-top:1px solid var(--vscode-panel-border);margin:11px 0}.signals{display:none}.signals.open{display:block}.signals div{font-size:11px;line-height:1.5;margin:3px 0}.ok{color:var(--vscode-testing-iconPassed)}.bad{color:var(--vscode-descriptionForeground)}@media(max-width:650px){body{padding:14px}.header{flex-direction:column}.grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="header"><div><h1>Connections</h1><div class="sub">Account readiness and MCP setup without storing credentials in DockyardOS.</div></div><div class="actions"><button class="secondary" id="refresh">Refresh local</button><button id="verify">Verify connections</button></div></div>
<div class="stats" id="stats"></div><div class="notice" id="notice"></div><div class="safety" id="safety"></div>
<section class="section"><h2>Provider accounts</h2><div class="sub">Local detection is automatic. “Verify connections” runs bounded read-only identity/status probes; it never deploys or mutates a provider.</div><div class="grid" id="providers"></div></section>
<section class="section"><h2>MCP connectors</h2><div class="sub">Configured is not the same as connected. DockyardOS only treats an MCP as connected after the active agent host verifies it in that host session.</div><div class="grid" id="mcps"></div></section>
<script nonce="${nonce}">
const vscode=acquireVsCodeApi();let model=${safeJson(model)};const $=id=>document.getElementById(id);const text=v=>document.createTextNode(String(v??''));
function button(label,type,id,secondary=false){const b=document.createElement('button');b.append(text(label));if(secondary)b.className='secondary';b.onclick=()=>{ $('notice').textContent=label+'…';vscode.postMessage({type,id})};return b}
function stateBadge(status){const e=document.createElement('span');e.className='state '+(status.level||'muted');e.append(text(status.label||status.state||'Unknown'));return e}
function stat(label,value){const e=document.createElement('span');e.className='stat';e.append(text(label+': '+value));return e}
function renderStats(){const s=model.summary||{};$('stats').replaceChildren(stat('Providers',s.providers||0),stat('Ready',s.providerReady||0),stat('Needs setup/login',s.providerAttention||0),stat('MCPs',s.mcps||0),stat('No-auth MCPs',s.noAuthMcps||0));}
function renderSafety(){const root=$('safety');root.replaceChildren();for(const value of model.safety||[]){const d=document.createElement('div');d.append(text('• '+value));root.append(d)}}
function providerCard(p){const c=document.createElement('article');c.className='card';const h=document.createElement('div');h.className='cardhead';const title=document.createElement('div');const n=document.createElement('h3');n.append(text(p.name));const id=document.createElement('div');id.className='id';id.append(text(p.id));title.append(n,id);h.append(title,stateBadge(p.status));c.append(h);const d=document.createElement('div');d.className='detail';d.append(text((p.liveChecked?'Live checked · ':'Local only · ')+(p.installed?'CLI installed':'CLI not detected')+(p.configured?' · configured':'')+(p.authenticated?' · authenticated':'')+(p.linked?' · linked':'')));c.append(d);const a=document.createElement('div');a.className='actions';if(p.canLogin)a.append(button(p.installed?'Login / reconnect':'Login after install','provider-login',p.id));if(p.setupUrl)a.append(button('Setup docs','provider-setup',p.id,true));if((p.signals||[]).length){const details=document.createElement('button');details.className='secondary';details.append(text('Details'));const box=document.createElement('div');box.className='signals';for(const s of p.signals){const row=document.createElement('div');row.className=s.ok?'ok':'bad';row.append(text((s.ok?'✓ ':'· ')+s.detail));box.append(row)}details.onclick=()=>box.classList.toggle('open');a.append(details);c.append(a,box)}else c.append(a);return c}
function mcpCard(m){const c=document.createElement('article');c.className='card';const h=document.createElement('div');h.className='cardhead';const title=document.createElement('div');const n=document.createElement('h3');n.append(text(m.name));const id=document.createElement('div');id.className='id';id.append(text(m.id));title.append(n,id);h.append(title,stateBadge(m.status));c.append(h);const chips=document.createElement('div');chips.className='chips';const cat=document.createElement('span');cat.className='chip';cat.append(text(m.category));chips.append(cat);if(m.auth==='none'){const noauth=document.createElement('span');noauth.className='chip';noauth.append(text('no auth'));chips.append(noauth)}c.append(chips);if(m.note){const d=document.createElement('div');d.className='detail';d.append(text(m.note));c.append(d)}if(m.endpoint){const d=document.createElement('div');d.className='detail';d.append(text('Endpoint: '+m.endpoint));c.append(d)}const a=document.createElement('div');a.className='actions';if(m.setupCommand)a.append(button('Install / configure','mcp-command',m.id));if(m.setupUrl)a.append(button('Setup docs','mcp-setup',m.id,true));if(m.endpoint)a.append(button('Copy endpoint','mcp-copy-endpoint',m.id,true));c.append(a);return c}
function render(){renderStats();renderSafety();$('providers').replaceChildren(...(model.providers||[]).map(providerCard));$('mcps').replaceChildren(...(model.mcps||[]).map(mcpCard));$('notice').textContent=model.liveChecked?'Live connection verification completed.':'Showing local readiness only. Use Verify connections for read-only account checks.'}
$('refresh').onclick=()=>{ $('notice').textContent='Refreshing local readiness…';vscode.postMessage({type:'refresh-local'})};$('verify').onclick=()=>{ $('notice').textContent='Running read-only live checks…';vscode.postMessage({type:'verify-live'})};window.addEventListener('message',event=>{const m=event.data||{};if(m.type==='model'){model=m.model;render();if(m.notice)$('notice').textContent=m.notice}else if(m.type==='notice')$('notice').textContent=m.text||'';else if(m.type==='error')$('notice').textContent=m.message||'Operation failed.'});render();
</script>
</body></html>`;
}

module.exports = { renderConnectionsHtml };
