import type { Candidate, HostId } from "./types.js";

const ALL_HOSTS: HostId[] = ["antigravity", "gemini-cli", "codex", "claude-code", "cursor", "opencode", "universal"];

export const creativeCatalog: Candidate[] = [
  {
    id: "taste-skill",
    displayName: "Taste Skill",
    category: "frontend-design",
    kind: "skill",
    trust: "maintainer",
    capabilities: [
      "ui-design",
      "frontend-design",
      "design-taste",
      "anti-slop",
      "visual-direction",
      "layout",
      "typography",
      "motion",
      "spacing",
      "redesign",
    ],
    tags: ["design", "frontend", "anti-generic", "premium-ui", "creative-ui"],
    stacks: ["web", "react", "nextjs", "vue", "svelte"],
    hosts: ALL_HOSTS,
    permissions: [],
    risk: "low",
    contextCost: "medium",
    maturity: 92,
    maintenance: 95,
    defaultChannel: "recommended",
    source: {
      type: "github",
      locator: "Leonxlnx/taste-skill",
      revisionStrategy: "pin-on-install",
      license: "MIT",
    },
  },
  {
    id: "awesome-design-skills",
    displayName: "Awesome Design Skills",
    category: "design-system-discovery",
    kind: "skill",
    trust: "maintainer",
    capabilities: [
      "ui-design",
      "design-system",
      "design-style-discovery",
      "visual-direction",
      "accessibility",
      "design-quality-gates",
    ],
    tags: ["design", "design-systems", "skill-library", "creative-ui", "style-selection"],
    stacks: ["web", "react", "nextjs", "vue", "svelte", "mobile"],
    hosts: ALL_HOSTS,
    permissions: [],
    risk: "low",
    contextCost: "small",
    maturity: 88,
    maintenance: 94,
    defaultChannel: "recommended",
    source: {
      type: "github",
      locator: "bergside/awesome-design-skills",
      revisionStrategy: "pin-on-install",
      license: "MIT",
    },
  },
  {
    id: "inspo-mcp",
    displayName: "Inspo MCP",
    category: "design-inspiration-mcp",
    kind: "mcp",
    trust: "official",
    capabilities: [
      "ui-design",
      "design-inspiration",
      "visual-reference",
      "macrostructure",
      "design-system",
      "design-tokens",
      "typography",
      "palette",
      "reference-components",
    ],
    tags: ["inspo", "design", "web", "reference-sites", "creative-ui", "read-only"],
    stacks: ["web", "react", "nextjs", "vue", "svelte"],
    hosts: ALL_HOSTS,
    permissions: ["network"],
    risk: "low",
    contextCost: "tiny",
    maturity: 94,
    maintenance: 98,
    defaultChannel: "recommended",
    source: {
      type: "website",
      locator: "https://inspomcp.dev/mcp",
      revisionStrategy: "live-metadata-only",
      license: "MIT",
    },
  },
];
