import type { HostAdapterDefinition } from "./host-types.js";

export const hostAdapters: HostAdapterDefinition[] = [
  {
    id: "antigravity",
    displayName: "Google Antigravity",
    command: "agy",
    integrationDirectory: "integrations/antigravity/plugin",
    integrationMode: "native-hooks",
    capabilities: ["hooks", "skills", "subagents", "rules", "checkpoint-injection", "approval-gates"],
    installHint: "agy plugin install ./integrations/antigravity/plugin",
    verifyHint: "agy plugin list && dockyard hosts context --id antigravity --json",
    notes: ["Primary DockyardOS host. Uses lifecycle hooks for automatic context restore, approval gating, autosave, and stop checkpoints."],
  },
  {
    id: "gemini-cli",
    displayName: "Gemini CLI",
    command: "gemini",
    integrationDirectory: "integrations/gemini-cli",
    integrationMode: "extension",
    capabilities: ["extensions", "hooks", "skills", "subagents", "policy", "checkpoint-context"],
    installHint: "gemini extensions install ./integrations/gemini-cli --auto-update",
    verifyHint: "gemini extensions list && dockyard hosts context --id gemini-cli --json",
    notes: ["Uses the official Gemini CLI extension format with context, commands, skills, hooks, and policy support."],
  },
  {
    id: "codex",
    displayName: "OpenAI Codex",
    command: "codex",
    integrationDirectory: "integrations/codex",
    integrationMode: "plugin",
    capabilities: ["plugins", "skills", "mcp", "agents-md", "checkpoint-context"],
    installHint: "Install or load ./integrations/codex as a Codex plugin/capability bundle, then keep DockyardOS CLI on PATH.",
    verifyHint: "codex mcp list; dockyard hosts context --id codex --json",
    notes: ["Uses portable Agent Skills and Codex plugin metadata; project guidance stays compact and points back to DockyardOS state."],
  },
  {
    id: "claude-code",
    displayName: "Claude Code",
    command: "claude",
    integrationDirectory: "integrations/claude-code",
    integrationMode: "instructions",
    capabilities: ["claude-md", "mcp", "subagents", "permission-modes", "checkpoint-context"],
    installHint: "Use the files in ./integrations/claude-code as the Claude Code project/user integration and keep DockyardOS CLI on PATH.",
    verifyHint: "claude mcp list; dockyard hosts context --id claude-code --json",
    notes: ["Avoids bypassing Claude Code permissions; DockyardOS provides context/checkpoints while Claude Code keeps its native approval boundary."],
  },
  {
    id: "cursor",
    displayName: "Cursor",
    command: "cursor",
    integrationDirectory: "integrations/cursor",
    integrationMode: "rules",
    capabilities: ["project-rules", "agents-md", "mcp", "checkpoint-context"],
    installHint: "Copy/link the DockyardOS Cursor rule from ./integrations/cursor into the project .cursor/rules directory.",
    verifyHint: "dockyard hosts context --id cursor --json",
    notes: ["Uses a small always-on project rule that restores DockyardOS state on demand instead of embedding large project history."],
  },
  {
    id: "opencode",
    displayName: "OpenCode",
    command: "opencode",
    integrationDirectory: "integrations/opencode",
    integrationMode: "agents",
    capabilities: ["agents", "mcp", "commands", "checkpoint-context"],
    installHint: "Copy/link ./integrations/opencode/.opencode into the target project or user OpenCode config.",
    verifyHint: "opencode mcp list; dockyard hosts context --id opencode --json",
    notes: ["Includes read-only review agents and DockyardOS-oriented instructions while preserving OpenCode permission controls."],
  },
  {
    id: "vscode",
    displayName: "Visual Studio Code",
    command: "code",
    integrationDirectory: "integrations/vscode",
    integrationMode: "extension",
    capabilities: ["extension-ui", "commands", "status-bar", "checkpoint-context", "team-controls"],
    installHint: "Build/package the VS Code extension in ./integrations/vscode and install the resulting VSIX once.",
    verifyHint: "Run 'DockyardOS: Doctor' and confirm the DockyardOS status bar item appears for an initialized workspace.",
    notes: ["VS Code is a control surface for DockyardOS and can coexist with whichever coding agent extension/CLI the user prefers."],
  },
];

export function hostAdapter(id: string): HostAdapterDefinition | undefined {
  return hostAdapters.find((adapter) => adapter.id === id);
}
