import type { ProviderAdapterDefinition } from "./types.js";

export const providerAdapters: ProviderAdapterDefinition[] = [
  {
    id: "github",
    displayName: "GitHub",
    cliCommands: ["gh"],
    configMarkers: [".git"],
    linkedMarkers: [".git/config"],
    authProbe: { command: "gh", args: ["auth", "status"], successReadiness: "authenticated", timeoutMs: 8_000 },
    statusProbe: { command: "git", args: ["remote", "get-url", "origin"], successReadiness: "linked", timeoutMs: 4_000 },
    capabilities: ["source", "issues", "pull-requests", "ci", "releases"],
    environments: ["local", "preview", "production"],
    freeTierCheck: "live-required",
  },
  {
    id: "vercel",
    displayName: "Vercel",
    cliCommands: ["vercel"],
    configMarkers: ["vercel.json", "vercel.ts", ".vercel"],
    linkedMarkers: [".vercel/project.json"],
    authProbe: { command: "vercel", args: ["whoami"], successReadiness: "authenticated", timeoutMs: 20_000, fallback: { command: "npx", args: ["-y", "vercel@latest", "whoami"] } },
    capabilities: ["web-hosting", "preview-deployments", "serverless", "domains"],
    environments: ["preview", "production"],
    freeTierCheck: "live-required",
    notes: ["Project linking is detected from .vercel/project.json without reading secrets."],
  },
  {
    id: "cloudflare",
    displayName: "Cloudflare",
    cliCommands: ["wrangler"],
    configMarkers: ["wrangler.toml", "wrangler.json", "wrangler.jsonc"],
    authProbe: { command: "wrangler", args: ["whoami", "--json"], successReadiness: "authenticated", timeoutMs: 30_000, fallback: { command: "npx", args: ["-y", "wrangler@latest", "whoami", "--json"] } },
    capabilities: ["dns", "cdn", "waf", "ddos", "edge-functions", "web-hosting", "object-storage"],
    environments: ["local", "preview", "production"],
    freeTierCheck: "live-required",
  },
  {
    id: "supabase",
    displayName: "Supabase",
    cliCommands: ["supabase"],
    configMarkers: ["supabase/config.toml"],
    authProbe: { command: "supabase", args: ["projects", "list", "--output", "json"], successReadiness: "authenticated", timeoutMs: 30_000, fallback: { command: "npx", args: ["-y", "supabase@latest", "projects", "list", "--output", "json"] } },
    capabilities: ["postgres", "auth", "object-storage", "realtime", "edge-functions"],
    environments: ["local", "preview", "production"],
    freeTierCheck: "live-required",
    notes: ["A local Supabase config proves configuration only; remote project linkage is not inferred from secret files."],
  },
  {
    id: "neon",
    displayName: "Neon",
    cliCommands: ["neon", "neonctl"],
    configMarkers: [".neon", "neon.json"],
    authProbe: { command: "neon", args: ["projects", "list", "--output", "json"], successReadiness: "authenticated", timeoutMs: 30_000, fallback: { command: "npx", args: ["-y", "neon@latest", "projects", "list", "--output", "json"] } },
    capabilities: ["postgres", "serverless-postgres"],
    environments: ["preview", "production"],
    freeTierCheck: "live-required",
    notes: ["The current CLI is `neon`; `neonctl` remains a compatibility alias. DockyardOS never passes Neon API keys as CLI arguments."],
  },
  {
    id: "firebase",
    displayName: "Firebase",
    cliCommands: ["firebase"],
    configMarkers: ["firebase.json"],
    linkedMarkers: [".firebaserc"],
    authProbe: { command: "firebase", args: ["projects:list", "--json"], successReadiness: "authenticated", timeoutMs: 30_000, fallback: { command: "npx", args: ["-y", "firebase-tools@latest", "projects:list", "--json"] } },
    capabilities: ["auth", "document-database", "object-storage", "functions", "web-hosting"],
    environments: ["local", "preview", "production"],
    freeTierCheck: "live-required",
  },
  {
    id: "appwrite",
    displayName: "Appwrite",
    cliCommands: ["appwrite"],
    configMarkers: ["appwrite.config.json"],
    linkedMarkers: ["appwrite.config.json"],
    authProbe: { command: "appwrite", args: ["whoami", "--json"], successReadiness: "authenticated", timeoutMs: 30_000, fallback: { command: "npx", args: ["-y", "appwrite-cli@latest", "whoami", "--json"] } },
    capabilities: ["auth", "database", "object-storage", "functions"],
    environments: ["local", "preview", "production"],
    freeTierCheck: "live-required",
  },
  {
    id: "pocketbase",
    displayName: "PocketBase",
    cliCommands: ["pocketbase"],
    configMarkers: ["pb_data", "pb_migrations"],
    capabilities: ["auth", "database", "object-storage", "realtime"],
    environments: ["local", "preview", "production"],
    freeTierCheck: "live-required",
    notes: ["PocketBase is primarily self-hosted; installation/config detection does not imply a managed deployment."],
  },
  {
    id: "render",
    displayName: "Render",
    cliCommands: ["render"],
    configMarkers: ["render.yaml", "render.yml"],
    authProbe: { command: "render", args: ["workspaces", "--output", "json"], successReadiness: "authenticated", timeoutMs: 10_000 },
    capabilities: ["web-hosting", "services", "postgres", "cron"],
    environments: ["preview", "production"],
    freeTierCheck: "live-required",
    notes: ["Render CLI authentication is verified through a read-only workspace listing; DockyardOS does not use secret deploy-hook URLs for P21 actions."],
  },
  {
    id: "railway",
    displayName: "Railway",
    cliCommands: ["railway"],
    configMarkers: ["railway.json", "railway.toml"],
    authProbe: { command: "railway", args: ["whoami"], successReadiness: "authenticated", timeoutMs: 30_000, fallback: { command: "npx", args: ["-y", "@railway/cli@latest", "whoami"] } },
    statusProbe: { command: "railway", args: ["status", "--json"], successReadiness: "linked", timeoutMs: 8_000 },
    capabilities: ["web-hosting", "services", "databases"],
    environments: ["preview", "production"],
    freeTierCheck: "live-required",
  },
  {
    id: "flyio",
    displayName: "Fly.io",
    cliCommands: ["fly", "flyctl"],
    configMarkers: ["fly.toml"],
    linkedMarkers: ["fly.toml"],
    authProbe: { command: "fly", args: ["auth", "whoami", "--json"], successReadiness: "authenticated", timeoutMs: 8_000 },
    capabilities: ["web-hosting", "services", "containers", "edge-deployments"],
    environments: ["preview", "production"],
    freeTierCheck: "live-required",
  },
  {
    id: "turso",
    displayName: "Turso",
    cliCommands: ["turso"],
    configMarkers: ["turso.toml"],
    capabilities: ["sqlite", "edge-database"],
    environments: ["local", "preview", "production"],
    freeTierCheck: "live-required",
  },
  {
    id: "sentry",
    displayName: "Sentry",
    cliCommands: ["sentry-cli"],
    configMarkers: [".sentryclirc", "sentry.client.config.ts", "sentry.server.config.ts", "sentry.properties"],
    capabilities: ["errors", "performance", "tracing"],
    environments: ["local", "preview", "production"],
    freeTierCheck: "live-required",
  },
  {
    id: "cloud-run",
    displayName: "Google Cloud Run",
    cliCommands: ["gcloud"],
    configMarkers: ["service.yaml", "cloudbuild.yaml"],
    capabilities: ["containers", "services", "serverless"],
    environments: ["preview", "production"],
    freeTierCheck: "live-required",
  },
  {
    id: "github-pages",
    displayName: "GitHub Pages",
    cliCommands: ["gh"],
    configMarkers: [".github/workflows/pages.yml", ".github/workflows/deploy-pages.yml"],
    capabilities: ["static-hosting"],
    environments: ["production"],
    freeTierCheck: "live-required",
  },
];

export function providerAdapter(id: string): ProviderAdapterDefinition | undefined {
  return providerAdapters.find((adapter) => adapter.id === id);
}
