import type { TeamRecipe } from "./types.js";

export const creativeRecipes: TeamRecipe[] = [
  {
    id: "cinematic-3d-web",
    displayName: "Cinematic 3D / 2.5D Web Experience",
    taskTypes: ["3d-web", "3d", "cinematic-web", "animation"],
    stacks: ["web", "react", "nextjs", "threejs", "r3f"],
    capabilities: [
      "ui-design",
      "design-inspiration",
      "visual-direction",
      "3d-web",
      "threejs",
      "r3f",
      "webgl",
      "motion-design",
      "scroll-storytelling",
      "video-generation",
      "frame-sequence",
      "2.5d",
      "responsive",
      "accessibility",
      "web-performance",
    ],
    required: ["playwright", "lighthouse"],
    preferred: [
      "threejs-r3f-cinematic",
      "gsap-scroll-storytelling",
      "frame-sequence-2-5d",
      "cinematic-asset-pipeline",
      "video-model-selection",
      "ffmpeg",
      "inspo-mcp",
      "taste-skill",
      "awesome-design-skills",
      "ui-ux-pro-max",
      "vercel-web-design-guidelines",
      "playwright-mcp",
    ],
    agents: [
      "research-agent",
      "architect-agent",
      "three-d-agent",
      "frontend-agent",
      "browser-qa-agent",
      "performance-agent",
      "accessibility-agent",
      "qa-reviewer-agent",
    ],
    securityLevel: "standard",
    workflowProfile: "full",
  },
  {
    id: "creative-web-ui",
    displayName: "Creative / Premium Web UI",
    taskTypes: ["landing-page", "new-project", "feature", "ui"],
    stacks: ["web", "react", "nextjs", "vue", "svelte"],
    capabilities: [
      "ui-design",
      "design-system",
      "design-inspiration",
      "visual-direction",
      "anti-slop",
      "responsive",
      "accessibility",
      "web-performance",
    ],
    required: ["playwright", "axe-core", "lighthouse"],
    preferred: [
      "inspo-mcp",
      "taste-skill",
      "awesome-design-skills",
      "ui-ux-pro-max",
      "vercel-web-design-guidelines",
      "shadcn",
      "playwright-mcp",
    ],
    agents: [
      "research-agent",
      "frontend-agent",
      "browser-qa-agent",
      "accessibility-agent",
      "performance-agent",
      "qa-reviewer-agent",
    ],
    securityLevel: "standard",
    workflowProfile: "standard",
  },
];
