import type { TeamRecipe } from "./types.js";

export const expandedRecipes: TeamRecipe[] = [
  {
    id: "enterprise-b2b-saas",
    displayName: "Enterprise B2B SaaS / SSO",
    taskTypes: ["enterprise-saas", "auth", "new-project"],
    stacks: ["web", "nextjs", "react", "postgres"],
    capabilities: ["organizations", "auth", "identity", "sso", "database", "privacy", "compliance", "auditability", "e2e"],
    required: ["owasp", "gitleaks", "osv-scanner", "playwright"],
    preferred: ["ui-ux-pro-max", "shadcn", "supabase-mcp-server", "github-mcp-server"],
    agents: ["product-manager-agent", "solution-architect-agent", "auth-agent", "database-agent", "privacy-agent", "compliance-agent", "security-reviewer-agent", "qa-reviewer-agent", "release-verifier-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "realtime-collaboration",
    displayName: "Realtime Collaboration / Presence App",
    taskTypes: ["realtime", "collaboration", "feature", "new-project"],
    stacks: ["web", "typescript", "postgres", "supabase", "workers"],
    capabilities: ["realtime", "websocket", "presence", "database", "auth", "resilience", "e2e"],
    required: ["owasp", "gitleaks", "osv-scanner", "playwright"],
    preferred: ["supabase-mcp-server", "cloudflare-observability-mcp"],
    agents: ["solution-architect-agent", "websocket-agent", "backend-agent", "database-agent", "auth-agent", "performance-reviewer-agent", "security-reviewer-agent", "qa-reviewer-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "rag-knowledge-system",
    displayName: "RAG / Knowledge Assistant",
    taskTypes: ["rag", "agent", "ai", "new-project"],
    stacks: ["python", "typescript", "web", "postgres", "mongodb"],
    capabilities: ["rag", "embeddings", "vector-database", "semantic-search", "evals", "prompt-injection", "observability"],
    required: ["owasp", "gitleaks", "osv-scanner"],
    preferred: ["mongodb-vector-search", "sentry-mcp", "agent-reach"],
    agents: ["ai-architect-agent", "rag-agent", "vector-search-agent", "backend-agent", "evals-agent", "prompt-safety-agent", "security-reviewer-agent", "qa-reviewer-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "data-pipeline-platform",
    displayName: "Data Pipeline / Analytics Platform",
    taskTypes: ["data-pipeline", "data", "new-project"],
    stacks: ["python", "postgres", "sql"],
    capabilities: ["etl", "elt", "pipelines", "data-quality", "schema", "sql", "observability"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["sqlfluff", "neon-mcp-server", "sentry-mcp"],
    agents: ["data-architect-agent", "data-engineer-agent", "database-agent", "data-quality-agent", "privacy-agent", "qa-reviewer-agent", "observability-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "ml-inference-service",
    displayName: "ML Training / Inference Service",
    taskTypes: ["machine-learning", "ml", "ai", "new-project"],
    stacks: ["python", "containers"],
    capabilities: ["training", "inference", "datasets", "model-packaging", "evals", "observability", "api"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["hf-cli", "docker-cli", "sentry-mcp"],
    agents: ["ai-architect-agent", "ml-engineer-agent", "data-engineer-agent", "evals-agent", "backend-agent", "security-reviewer-agent", "observability-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "payments-billing-feature",
    displayName: "Payments / Billing Integration",
    taskTypes: ["payments", "billing", "feature"],
    stacks: ["web", "typescript", "postgres"],
    capabilities: ["payments", "checkout", "billing", "webhooks", "idempotency", "database", "security"],
    required: ["owasp", "gitleaks", "osv-scanner"],
    preferred: ["superpowers", "spectral-openapi"],
    agents: ["payments-agent", "backend-agent", "database-agent", "api-contract-agent", "threat-model-agent", "security-reviewer-agent", "qa-reviewer-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "identity-auth-feature",
    displayName: "Authentication / Identity Integration",
    taskTypes: ["auth", "identity", "feature"],
    stacks: ["web", "mobile", "postgres"],
    capabilities: ["auth", "identity", "oauth", "mfa", "authorization", "session-security"],
    required: ["owasp", "gitleaks", "osv-scanner"],
    preferred: ["superpowers", "supabase-mcp-server"],
    agents: ["auth-agent", "solution-architect-agent", "backend-agent", "database-rls-reviewer-agent", "threat-model-agent", "security-reviewer-agent", "qa-reviewer-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "file-media-platform",
    displayName: "File Upload / Media Platform",
    taskTypes: ["storage", "media", "feature", "new-project"],
    stacks: ["web", "typescript"],
    capabilities: ["object-storage", "file-upload", "media-storage", "cdn", "auth", "security", "e2e"],
    required: ["owasp", "gitleaks", "osv-scanner", "playwright"],
    preferred: ["cloudflare-bindings-mcp", "supabase-mcp-server"],
    agents: ["solution-architect-agent", "backend-agent", "auth-agent", "privacy-agent", "security-reviewer-agent", "browser-qa-agent", "performance-reviewer-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "background-job-platform",
    displayName: "Background Jobs / Event Workflows",
    taskTypes: ["background-jobs", "jobs", "feature"],
    stacks: ["typescript", "node", "python"],
    capabilities: ["background-jobs", "queues", "events", "scheduling", "idempotency", "observability"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["superpowers"],
    agents: ["solution-architect-agent", "backend-agent", "sre-agent", "observability-agent", "qa-reviewer-agent"],
    securityLevel: "standard",
    workflowProfile: "full",
  },
  {
    id: "kubernetes-platform",
    displayName: "Kubernetes Service Platform",
    taskTypes: ["kubernetes", "infrastructure", "new-project", "migration"],
    stacks: ["kubernetes", "docker"],
    capabilities: ["kubernetes", "containers", "helm", "infrastructure", "deployment", "observability", "reliability"],
    required: ["gitleaks", "osv-scanner", "trivy"],
    preferred: ["docker-cli", "kubectl", "helm", "opentofu"],
    agents: ["cloud-architect-agent", "kubernetes-agent", "infra-agent", "sre-agent", "supply-chain-security-agent", "security-reviewer-agent", "release-verifier-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "cloud-infrastructure",
    displayName: "Cloud Infrastructure / IaC",
    taskTypes: ["infrastructure", "iac", "migration"],
    stacks: ["terraform", "aws", "azure", "gcp"],
    capabilities: ["infrastructure", "terraform", "iac", "networking", "deployment", "secrets", "observability", "cost"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["terraform", "opentofu"],
    agents: ["cloud-architect-agent", "terraform-agent", "infra-agent", "cost-agent", "secrets-reviewer-agent", "security-reviewer-agent", "release-verifier-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "developer-cli-sdk",
    displayName: "Developer CLI + SDK",
    taskTypes: ["cli", "sdk", "developer-tool", "new-project"],
    stacks: ["typescript", "python", "go", "rust"],
    capabilities: ["cli", "sdk-design", "client-libraries", "automation", "documentation", "release"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["superpowers"],
    agents: ["solution-architect-agent", "cli-agent", "sdk-agent", "dx-agent", "docs-agent", "qa-reviewer-agent", "release-manager-agent"],
    securityLevel: "standard",
    workflowProfile: "full",
  },
  {
    id: "mcp-server-development",
    displayName: "MCP Server / Connector",
    taskTypes: ["mcp", "agent", "new-project"],
    stacks: ["typescript", "python"],
    capabilities: ["mcp-server", "tool-design", "resource-design", "protocol", "permission-boundaries", "testing"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["anthropic-mcp-builder", "microsoft-mcp-builder", "mcp-official-registry-feed"],
    agents: ["mcp-architect-agent", "backend-agent", "mcp-reviewer-agent", "prompt-safety-agent", "security-reviewer-agent", "qa-reviewer-agent", "docs-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "ide-extension",
    displayName: "VS Code / IDE Extension",
    taskTypes: ["ide-extension", "extension", "new-project"],
    stacks: ["typescript", "vscode"],
    capabilities: ["vscode-extension", "ide-extension", "commands", "webviews", "tooling", "release"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["superpowers", "playwright-mcp"],
    agents: ["extension-agent", "dx-agent", "frontend-reviewer-agent", "security-reviewer-agent", "qa-reviewer-agent", "release-manager-agent"],
    securityLevel: "standard",
    workflowProfile: "full",
  },
  {
    id: "browser-extension",
    displayName: "Browser Extension",
    taskTypes: ["browser-extension", "extension", "new-project"],
    stacks: ["web", "typescript", "browser-extension"],
    capabilities: ["browser-extension", "manifest-v3", "content-scripts", "permissions", "browser-automation"],
    required: ["owasp", "gitleaks", "osv-scanner", "playwright"],
    preferred: ["playwright-mcp"],
    agents: ["browser-extension-agent", "frontend-agent", "privacy-agent", "security-reviewer-agent", "browser-qa-agent", "release-verifier-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "monorepo-platform",
    displayName: "Monorepo Architecture / Cleanup",
    taskTypes: ["monorepo", "refactor", "migration"],
    stacks: ["typescript", "javascript"],
    capabilities: ["monorepo", "workspace", "build-graph", "dependency-boundaries", "dead-code", "regression"],
    required: [],
    preferred: ["dependency-cruiser", "knip", "superpowers"],
    agents: ["monorepo-agent", "architect-agent", "dependency-upgrade-agent", "refactor-agent", "qa-reviewer-agent", "dx-agent"],
    securityLevel: "standard",
    workflowProfile: "full",
  },
  {
    id: "dependency-upgrade",
    displayName: "Dependency / Framework Upgrade",
    taskTypes: ["dependency-upgrade", "upgrade", "migration"],
    stacks: [],
    capabilities: ["dependency-upgrade", "compatibility", "codemod", "regression", "supply-chain-security"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["superpowers", "trivy"],
    agents: ["dependency-upgrade-agent", "migration-planner-agent", "supply-chain-security-agent", "qa-reviewer-agent", "migration-verifier-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "search-platform",
    displayName: "Search / Retrieval Platform",
    taskTypes: ["search", "feature", "new-project"],
    stacks: ["postgres", "mongodb", "python", "typescript"],
    capabilities: ["full-text-search", "ranking", "indexing", "semantic-search", "vector-search", "search-quality"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["mongodb-atlas-search", "mongodb-vector-search"],
    agents: ["data-architect-agent", "search-agent", "vector-search-agent", "backend-agent", "data-quality-agent", "performance-reviewer-agent", "qa-reviewer-agent"],
    securityLevel: "standard",
    workflowProfile: "full",
  },
  {
    id: "incident-response",
    displayName: "Production Incident Investigation",
    taskTypes: ["incident", "outage", "production-debug"],
    stacks: [],
    capabilities: ["incident-response", "triage", "logs", "tracing", "root-cause", "mitigation", "rollback"],
    required: [],
    preferred: ["sentry-mcp", "cloudflare-observability-mcp"],
    agents: ["incident-agent", "sre-agent", "debugger-agent", "observability-agent", "security-reviewer-agent", "release-verifier-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "document-automation",
    displayName: "Document / Office Artifact Automation",
    taskTypes: ["document", "artifact", "feature"],
    stacks: [],
    capabilities: ["pdf", "documents", "spreadsheets", "presentations", "artifact-generation", "editing"],
    required: [],
    preferred: ["anthropic-pdf", "anthropic-document-workflows", "anthropic-spreadsheet-workflows", "anthropic-presentation-workflows"],
    agents: ["requirements-agent", "technical-writer-agent", "qa-reviewer-agent"],
    securityLevel: "standard",
    workflowProfile: "standard",
  },
  {
    id: "expo-mobile-release",
    displayName: "Expo / React Native Production App",
    taskTypes: ["mobile", "mobile-release", "new-project"],
    stacks: ["expo", "react-native", "mobile"],
    capabilities: ["expo", "mobile-ui", "navigation", "mobile-qa", "mobile-release", "ota-updates", "observability"],
    required: ["owasp", "gitleaks", "osv-scanner"],
    preferred: ["expo-router", "expo-native-ui", "callstack-react-native-best-practices", "callstack-rn-testing", "eas-update-insights"],
    agents: ["mobile-agent", "device-automation-agent", "mobile-qa-agent", "performance-reviewer-agent", "security-reviewer-agent", "release-manager-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "desktop-app",
    displayName: "Desktop Application",
    taskTypes: ["desktop", "new-project", "feature"],
    stacks: ["electron", "tauri", "typescript", "rust"],
    capabilities: ["desktop-app", "native-integration", "ui-design", "security", "release"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["ui-ux-pro-max", "superpowers"],
    agents: ["desktop-agent", "solution-architect-agent", "frontend-agent", "security-reviewer-agent", "qa-reviewer-agent", "release-manager-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
  {
    id: "multiplayer-game",
    displayName: "Multiplayer Game / Realtime Game Backend",
    taskTypes: ["game", "multiplayer", "new-project"],
    stacks: ["mobile", "web", "typescript", "go"],
    capabilities: ["gameplay", "multiplayer", "realtime", "state", "networking", "performance", "security"],
    required: ["gitleaks", "osv-scanner"],
    preferred: ["superpowers"],
    agents: ["game-agent", "solution-architect-agent", "websocket-agent", "backend-agent", "performance-reviewer-agent", "security-reviewer-agent", "qa-reviewer-agent"],
    securityLevel: "high",
    workflowProfile: "full",
  },
];
